<a href="https://colab.research.google.com/github/Chhavi-Projects/Data_science_internship_modules/blob/main/Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries and upload the CSV

In [2]:
from google.colab import files

uploaded = files.upload()

Saving customer_master.csv to customer_master.csv

In [3]:
import pandas as pd
import numpy as np

filename = next(iter(uploaded))
df = pd.read_csv(filename)

print(df.head())

   customer_id customer_name  customer_age  gender customer_segment  \
0  CUST-000001  Donna Miller            54  Female         Consumer
1  CUST-000002  Joseph James            61    Male         Consumer
2  CUST-000003  Daniel Smith            47    Male         Consumer
3  CUST-000004   David Lopez            30    Male              VIP
4  CUST-000005  Dakota Davis            55  Female         Consumer

    customer_city customer_state customer_country region  \
0      Laurenland          Dubai              UAE  South
1      Lake Peter   Lower Saxony          Germany  North
2        Seanview    North Rhine          Germany   West
3    Hawkinshaven   Pennsylvania              USA   East
4  New Carlymouth        Florida              USA  South

   customer_postal_code  customer_acquisition_cost
0                 11253                      13.58
1                 47778                      27.45
2                 13900                      31.53
3                 53984                      16.02
4                 50994                      41.34

Check missing values and duplicates.

In [5]:
print("Missing Values:\n", df.isnull().sum())
print("\nTotal Missing Values:", df.isnull().sum().sum())
print("\nDuplicate Rows:", df.duplicated().sum())

Missing Values:
 customer_id                  0
customer_name                0
customer_age                 0
gender                       0
customer_segment             0
customer_city                0
customer_state               0
customer_country             0
region                       0
customer_postal_code         0
customer_acquisition_cost    0
dtype: int64

Total Missing Values: 0

Duplicate Rows: 0

Explore the dataset.

In [4]:
print("Dataset Shape:", df.shape)
print("\nColumn Names:", df.columns.tolist())
print("\nDataset Information:")
df.info()
print("\nFirst 5 Rows:")
display(df.head())
print("\nStatistical Summary:")
display(df.describe(include="all"))

Dataset Shape: (25000, 11)

Column Names: ['customer_id', 'customer_name', 'customer_age', 'gender', 'customer_segment', 'customer_city', 'customer_state', 'customer_country', 'region', 'customer_postal_code', 'customer_acquisition_cost']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  object
 1   customer_name              25000 non-null  object
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  object
 4   customer_segment           25000 non-null  object
 5   customer_city              25000 non-null  object
 6   customer_state             25000 non-null  object
 7   customer_country           25000 non-null  object
 8   region                     25000 non-null  object
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 2.1+ MB

First 5 Rows:

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

Statistical Summary:

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
count,25000,25000,25000.000000,25000,25000,25000,25000,25000,25000,25000.000000,25000.000000
unique,25000,21631,NaN,3,4,15555,38,7,5,NaN,NaN
top,CUST-025000,John Smith,NaN,Female,Consumer,South Michael,Pennsylvania,USA,South,NaN,NaN
freq,1,17,NaN,12048,13638,30,1632,14925,7996,NaN,NaN
mean,NaN,NaN,45.907840,NaN,NaN,NaN,NaN,NaN,NaN,50183.066400,42.159750
std,NaN,NaN,16.454286,NaN,NaN,NaN,NaN,NaN,NaN,28596.584321,21.692648
min,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,516.000000,5.010000
25%,NaN,NaN,32.000000,NaN,NaN,NaN,NaN,NaN,NaN,25374.500000,23.297500
50%,NaN,NaN,46.000000,NaN,NaN,NaN,NaN,NaN,NaN,50303.000000,41.980000
75%,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,74845.500000,61.130000
max,NaN,NaN,74.000000,NaN,NaN,NaN,NaN,NaN,NaN,99950.000000,79.990000

Clean and organize the data.

In [9]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df = df.drop_duplicates()
df["customer_name"] = df["customer_name"].str.strip()
df["gender"] = df["gender"].str.strip()
df["customer_segment"] = df["customer_segment"].str.strip()

print("Data cleaned successfully!")
display(df.head())

Data cleaned successfully!

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

Analyzing customer data using NumPy and Pandas.

In [10]:
ages = df["customer_age"].to_numpy()
costs = df["customer_acquisition_cost"].to_numpy()

print("Average Customer Age:", np.mean(ages))
print("Minimum Age:", np.min(ages))
print("Maximum Age:", np.max(ages))
print("Average Acquisition Cost:", np.mean(costs))
print("Median Acquisition Cost:", np.median(costs))
print("Standard Deviation of Cost:", np.std(costs))

Average Customer Age: 45.90784
Minimum Age: 18
Maximum Age: 74
Average Acquisition Cost: 42.1597504
Median Acquisition Cost: 41.98
Standard Deviation of Cost: 21.692214524517773

Analyzing customer segments.

In [11]:
print("Customers by Segment:")
display(df["customer_segment"].value_counts())

print("\nAverage Acquisition Cost by Segment:")
display(df.groupby("customer_segment")["customer_acquisition_cost"].mean().round(2))

Customers by Segment:

customer_segment
Consumer    13638
Premium      6301
VIP          2542
Business     2519
Name: count, dtype: int64

Average Acquisition Cost by Segment:

customer_segment
Business    42.38
Consumer    42.26
Premium     41.94
VIP         41.93
Name: customer_acquisition_cost, dtype: float64

Analyzing Customer Geography.

In [12]:
print("Customers by Country:")
display(df["customer_country"].value_counts())

print("\nCustomers by Region:")
display(df["region"].value_counts())

print("\nTop 10 Customer Cities:")
display(df["customer_city"].value_counts().head(10))

Customers by Country:

customer_country
USA          14925
UK            3701
Germany       2046
Canada        1279
Australia     1233
India         1041
UAE            775
Name: count, dtype: int64

Customers by Region:

region
South      7996
Central    5358
West       4750
East       3874
North      3022
Name: count, dtype: int64

Top 10 Customer Cities:

customer_city
South Michael       30
Lake Michael        30
East Michael        23
Port Michael        21
South James         20
New David           19
New Robert          18
North David         17
New John            17
West Christopher    17
Name: count, dtype: int64

Analyzing Using Age groups.

In [13]:
df["age_group"] = pd.cut(
    df["customer_age"],
    bins=[17, 25, 35, 45, 55, 65, 100],
    labels=["18-25", "26-35", "36-45", "46-55", "56-65", "66+"]
)

display(df["age_group"].value_counts().sort_index())

age_group
18-25    3509
26-35    4426
36-45    4422
46-55    4356
56-65    4398
66+      3889
Name: count, dtype: int64